### ISSUE TITLE
Will it work in Angular 5?

### ISSUE THREAD

**Issue by ghost** [beyondsanity/ngx-freshchat#1]
Can we use this package in Angular 5 App? If not do you have Angular 5 version?

**Comment by beyondsanity** [comment]
Sorry for the late response. I think it might work but it will raise a warning while installing. Have you tried it?

**Comment by sandrocsimas** [comment]
I'm getting this warning and the chat is not appearing:
````
A cookie associated with a cross-site resource at http://freshchat.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
````

**Comment by sandrocsimas** [comment]
> Can we use this package in Angular 5 App? If not do you have Angular 5 version?
I just tried with Angular 8 and yes, it's working!
