### ISSUE TITLE
Inifinite angular app reload

### ISSUE THREAD

**Issue by brankoiliccc** [beyondsanity/ngx-freshchat#16]
1. Angular 10.0.4
2. ngx-freshchat 0.2.0

```
@Injectable({
  providedIn: 'root'
})
export class FreshchatService {
    constructor(private chat: NgxFreshChatService,
    private companyService: CompanyService) {
    this.companyService.getValue.pipe(takeUntil(this.unsubscribe)).subscribe((company: Company) => {

        this.initilizeFreshChate(company.allCompanySettings.freshChatToken, company.allCompanySettings.freshChatUrl, company.allCompanySettings.freshChatConfigJson);
    })
  }

  private initilizeFreshChate(freshChatToken: string, freshChatUrl: string, config: any) {
    const options: FCInitObject = {} as FCInitObject;
    options.token = freshChatToken;
    options.host = freshChatUrl;
    options.config = config;
    this.chat.init(options)
      .subscribe(
        () => console.log('FreshChat is ready!')
      );
  }
}
```

```
export class AppModule {
  // We inject the service here to keep it alive whole time
  constructor(public _googleAnalyticsService: GoogleAnalyticsService, 
    public jsonLdService: JsonLdService,
    public freshchatService: FreshchatService) { } 

}
```

**Comment by WillPoulson** [comment]
Hi,

Thanks for reporting an issue.

Are you including the FreshchatService into your app modules NgModule imports list?

**Comment by brankoiliccc** [comment]
No

**Comment by WillPoulson** [comment]
Please try to import the library inside your desired module:

```
@NgModule({
    imports: [
        ...
        NgxFreshChatModule
        ...
```

Rather than including it in the constructor of the AppModule.

**Comment by brankoiliccc** [comment]
Hmm how would that work. What i need is to have chat visible on every page. That is why i imported in AppModule and used the service in AppModule constructor. Should i create another module just for freshchat and import that module into AppModule to keep it running the whole time ?

**Comment by WillPoulson** [comment]
After following the steps from my previous comment.

Import your custom FreshchatService service into your **AppComponent** constructor. 
Then call your custom initilizeFreshChate() function in an ngOnInit. 

```
export class AppComponent implements OnInit {
  constructor(
    public freshchatService: FreshchatService,
  ) {}

  ngOnInit() {
    this.freshchatService.initilizeFreshChate()
  }
}
```

This will load when your app first loads showing the chat widget on all pages of your app 👍

**Comment by brankoiliccc** [comment]
Same issue. App keeps reloading indefinitely. The problem is in bad configuration. When i use bad token or host NgxFreshChat crashes entire app.

**Comment by brankoiliccc** [comment]
Correction. This happens only if host property is undefined. I will Hardcode it to use https://wchat.freshchat.com

**Comment by beyondsanity** [comment]
Hello @brankoiliccc,

Thanks for reporting the issue.
I'm not sure about letting the app failing silently as someone might be having the same issue and no info about the error.
I think the best solution would be to detect the issue and emit error on the observable, I'll try to work on it.

In the meantime I suggest you to add a check for credentials before trying to initializing the library.

**Comment by brankoiliccc** [comment]
Yes. I have already made the corrections in my app. Thnx
