### ISSUE TITLE
Angular 11 update

### ISSUE THREAD

**Issue by brankoiliccc** [beyondsanity/ngx-freshchat#18]
Right now it is not possible to upgrade to angular 11 with ngx-freshchat.

`Package "ngx-freshchat" has an incompatible peer dependency to "@angular/common" (requires "^6.0.0-rc.0 || ^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0" (extended), would install "11.0.5").
                  Package "ngx-freshchat" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0-rc.0 || ^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0" (extended), would install "11.0.5").`

**Comment by avialonn** [comment]
@brankoiliccc , any way around it?

**Comment by WillPoulson** [comment]
I'll take a look at upgrading this later, this should only be an NPM warning and it should still continue to function.

**Comment by beyondsanity** [comment]
I'm sorry for the long absence. The 0.4.0 release should fix this.
