### ISSUE TITLE
How to get restoreId

### ISSUE THREAD

**Issue by alexandrkrucheniuk** [beyondsanity/ngx-freshchat#2]
@beyondsanity  Hey 
Can you please advice is there any ability to get  **_restoreId_** when_ user is created?

In Freshchat WebMessenger API they have:
> window.fcWidget.on("user:created", function(resp) {
console.log('User has been created');
//Function to do some task
});

AFAIK there is only one way how to get the restoreId.

**Comment by beyondsanity** [comment]
Hello, 

I'm not using this feature but it should works this way:

`
    this.chat.init({
      token: [MY_FRESHCHAT_TOKEN],
      host:[MY_FRESHCHAT_URL],
      restoreId: restoreId ? restoreId : null
    })
    .pipe(
      flatMap(
        () => this.chat.setUserProperties([MY_USER_DATA])
      )
    )
    .subscribe(
      data => {
        if (data.restoreId) {
          // Update restoreId in your database
        }
      },
      err => console.log(err)
    );
`

**Comment by beyondsanity** [comment]
fixed in 0.1.0
